on: push
jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Robot Framework Tests
    steps:
      - uses: actions/checkout@v3
      - run: chmod 777 reports
      - uses: isbang/compose-action@v1.3.2
        with:
          up-flags: "--abort-on-container-exit --exit-code-from robot"
      - name: Upload test results
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: reports
          path: reports
  generate_report:
    if: always()
    needs: [test]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download reports
      uses: actions/download-artifact@v1
      with:
        name: reports
    - name: Send report to commit
      uses: joonvena/robotframework-reporter-action@v2.1
      with:
        gh_access_token: ${{ secrets.GITHUB_TOKEN }}